services:
  db:
    image: couchbase:community
    container_name: db
    ports:
      - "8091-8097:8091-8097"
      - "9123:9123"
      - "11207:11207"
      - "11210:11210"
      - "11280:11280"
      - "18091-18097:18091-18097"
      - "5984:5984"
    volumes:
      - ./db-data:/opt/couchbase/var
    restart: unless-stopped

